services:
  webapp:
    tty: true
    image: container-discovery-test:latest
    build:
      context: .
      dockerfile: docker/trixie/Dockerfile
      target: test
      args:
        - GIT_COMMIT
    environment:
      - COVERAGE=${COVERAGE:-on}
      - FEATURE
      - NUM_PROCESSES=${NUM_PROCESSES:-2}
      - USE_RSPEC
    volumes:
      - ./blacklight-cornell:/workspaces/blacklight-cornell:cached
      - ${RAILS_ENV_FILE}:/custom_mnt/.env:ro
      - ${RAILS_ENV_FILE}:/workspaces/blacklight-cornell/.env:ro
      - ./mount:/app:cached
    working_dir: /workspaces/blacklight-cornell
