version: '3.8'
services:
  webapp:
    extends:
      file: docker-compose-local-gems.yaml
      service: webapp
    volumes:
      - ./blacklight-cornell:/workspaces/blacklight-cornell:cached
      - ${RAILS_ENV_FILE}:/workspaces/blacklight-cornell/.env:ro
      - ./mount/blacklight-cornell-requests:/app/blacklight-cornell-requests:cached
      - ./mount/cul-my-account:/app/cul-my-account:cached
    environment:
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
    ports:
      - 9292:9292
    working_dir: /workspaces/blacklight-cornell
    command:
      - /bin/bash
      - -c
      - |
        bundle exec rake db:migrate
        bundle exec rake assets:precompile
        bundle exec puma
    stdin_open: true
