version: '3.8'

services:
  webapp:
    tty: true
    image: container-discovery:latest
    build:
      context: .
      dockerfile: docker/bookworm/Dockerfile
      args:
        - GIT_COMMIT
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RUN_CRON=true
    ports:
      - 9292:9292
    volumes:
      - ${AWS_CREDENTIALS}:/custom_mnt/credentials:ro
