1n:
    short_message: Available
    long_message: Not checked out
1r:
    short_message: 'Available (Requests: %REQS)'
    long_message: 'Not checked out (Requests: %REQS)'
2n:
    short_message: '%ENUM Checked out, due %DATE'
    long_message: 'Checked out, due %DATE - Recall, or try Borrow Direct or ILL.'
    services:
        -   recall_hold
        -   borrow_direct
        -   ill
2r:
    short_message: 'Checked out, due %DATE (Requests: %REQS)'
    long_message: 'Checked out, due %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
    services:
        -   borrow_direct
        -   ill
3n:
    short_message: '%ENUM Checked out, due %DATE'
    long_message: 'Checked out, due %DATE - Recall, or try Borrow Direct or ILL.'
    services:
        -   recall_hold
        -   borrow_direct
        -   ill
3r:
    short_message: 'Checked out, due %DATE (Requests: %REQS)'
    long_message: 'Checked out, due %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
    services:
        -   borrow_direct
        -   ill
4n:
    short_message: '%ENUM Overdue as of %DATE'
    long_message: 'Overdue as of %DATE - Recall, or try Borrow Direct.'
    services:
        -   recall_hold
        -   borrow_direct
4r:
    short_message: 'Overdue as of %DATE (Requests: %REQS)'
    long_message: 'Overdue as of %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
    services:
        -   borrow_direct
        -   ill
5n:
        short_message: '%ENUM Overdue as of  %DATE (Requests: %REQS)'
        long_message: 'Checked out, due %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
#        short_message: 'Requests: %REQS'
#        long_message: 'Requests: %REQS'
5r:
        short_message: 'Checked out, due %DATE (Requests: %REQS)'
        long_message: 'Checked out, due %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
6n:
        short_message: '%ENUM Checked out, due %DATE (Requests: %REQS)'
        long_message: 'Checked out, due %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
#        short_message: 'Requests: %REQS'
#        long_message: 'Requests: %REQS'
6r:
        short_message: 'Checked out, due %DATE (Requests: %REQS)'
        long_message: 'Checked out, due %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
7n:
        short_message: '%ENUM On hold (Requests: %REQS)'
        long_message: 'On hold. Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
7r:
        short_message: '%ENUM On hold. (Requests: %REQS)'
        long_message: 'On hold. (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
8n:
        short_message: '%ENUM In transit %DATE'
        long_message: 'In transit %DATE Requests: (%REQS). Place a hold request.'
        services:
            -   recall_hold
8r:
        short_message: 'In transit %DATE (Requests: %REQS)'
        long_message: 'In transit %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
9n:
        short_message: '%ENUM In transit %DATE'
        long_message: 'In transit to %LOC %DATE (Requests: %REQS). Place a hold request.'
        services:
            -   recall_hold
9r:
        short_message: 'In transit %DATE (Requests: %REQS)'
        long_message: 'In transit to %LOC %DATE (Requests: %REQS). Try Borrow Direct.'
        services:
            -   borrow_direct
10n:
        short_message: '%ENUM In transit  %DATE Requests: (%REQS).'
        long_message: 'In transit to %LOC %DATE. Place a hold request.'
        services:
            -   recall_hold
10r:
        short_message: 'In transit to %LOC %DATE (Requests: %REQS)'
        long_message: 'In transit to %LOC %DATE (Requests: %REQS). Try Borrow Direct.'
        services:
            -   borrow_direct
11n:
        short_message: '%ENUM Returned %DATE'
        long_message: 'Returned %DATE'
11r:
        short_message: 'Returned %DATE (Requests: %REQS)'
        long_message: 'Returned %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
12n:
        short_message: '%ENUM Missing %SDATE (Requests: %REQS)'
        long_message: 'Missing %DATE. Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
12r:
        short_message: 'Missing %SDATE (Requests: %REQS)'
        long_message: 'Missing %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
13n:
        short_message: '%ENUM Unavailable %SDATE'
        long_message: 'Unavailable %DATE. Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
13r:
        short_message: 'Unavailable %DATE (Requests: %REQS)'
        long_message: 'Unavailable %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
14n:
        short_message: '%ENUM Unavailable %SDATE'
        long_message: 'Unavailable %DATE. Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
14r:
        short_message: 'Unavailable %DATE (Requests: %REQS)'
        long_message: 'Unavailable %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
15n:
        short_message: '%ENUM Unavailable %SDATE'
        long_message: 'Unavailable %DATE. Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
18n:
        short_message: '%ENUM Sent to  bindery for 1 month on %DATE'
        long_message: 'Sent to bindery for 1 month on %DATE. Try Borrow Direct or ILL. '
        services:
            -   borrow_direct
            -   ill
18r:
        short_message: '%ENUM Sent to bindery for 1 month on %DATE (Requests: %REQS)'
        long_message: 'Sent to bindery for 1 month on %DATE (Requests: %REQS). Try Borrow Direct or ILL.'
        services:
            -   borrow_direct
            -   ill
19n:
        short_message: '%ENUM Cataloging Review %DATE'
        long_message: 'Sent for Cataloging Review. Try Borrow Direct or ILL. '
        services:
            -   borrow_direct
            -   ill
19r:
        short_message: 'Cataloging Review %DATE'
        long_message: 'Sent for Cataloging Review. Try Borrow Direct or ILL. '
        services:
            -   borrow_direct
            -   ill
20n:
        short_message: '%ENUM Circulation Review %DATE'
        long_message: 'Sent for Cataloging Review. Try Borrow Direct or ILL. '
        services:
            -   borrow_direct
            -   ill
22n:
        short_message: '%ENUM In Process %DATE'
        long_message: 'In Process %DATE. Place an In Process item request.'
        services:
            -   in_process
22r:
        short_message: '%ENUM In Process %DATE (Requests: %REQS)'
        long_message: 'In Process %DATE (Requests: %REQS). Place an In Process item request.'
        services:
            -   in_process
23n:
        short_message: '%ENUM Requested %DATE (Requests: %REQS)'
        long_message: 'In Process %DATE. Place an In Process item request.'
        services:
            -   in_process
23r:
        short_message: 'Requested %DATE (Requests: %REQS)'
        long_message: 'In Process %DATE (Requests: %REQS). Place an In Process item request.'
        services:
            -   in_process
25n:
        short_message: '%ENUM Requested %DATE (Requests: %REQS)'
        long_message: 'Requested %DATE (Requests: %REQS)'
        services:
            -   in_process
25r:
        short_message: '%ENUM Requested %DATE (Requests: %REQS)'
        long_message: 'In Process %DATE (Requests: %REQS). Place an In Process item request.'
        services:
            -   in_process
