# Add sensitive data for API connections here and save as search_apis.yml
# This new file will not be tracked by Git.
# Values are used by config/initializers/bento_search.rb

worldcat_api_key: <%= ENV['WORLDCAT_API_KEY'] %>

summon_access_id:  <%= ENV['SUMMON_ACCESS_ID'] %>
summon_secret_key:  <%= ENV['SUMMON_SECRET_KEY'] %>
