source "https://rubygems.org"
ruby "3.2.2"
gem "rails", "~> 6.1.7"

gem "activerecord-session_store", ">= 2.0.0"
gem "addressable", ">= 2.8.0"
gem "appsignal", "~> 3.3.2" #, '2.11.10'
gem "aws-sdk-s3", "~> 1.143"
gem "bento_search", "~> 2.0.0.rc1"
gem "blacklight" # , '7.29.0'
gem "blacklight-hierarchy"
gem "blacklight-marc", "~> 6.3"
gem "blacklight_range_limit", "~> 8.5.0"
gem "blacklight_unapi", :git => "https://github.com/cul-it/blacklight-unapi", :branch => "BL7-upgrade"
gem "bootstrap", "~> 4.6"
gem "capistrano", "~> 3.18"
gem "capistrano-rails", "~> 1.6"
gem 'capistrano-rvm'
gem "celluloid", "0.17.4" # Required for bento_search multisearcher
gem "coffee-rails", "~> 4.0"
gem "concurrent-ruby", "1.2.3", require: "concurrent"
gem 'devise', '>= 4.7.0'
gem 'devise-guests', '~> 0.3'
gem "dotenv-rails", "2.8.1" # NOTE: unpinning this and letting it drift to latest (v3.x) breaks SAML login!
gem "ebsco-eds"
gem "ffi"
gem "font-awesome-rails"
gem "exception_notification"
gem "haml" 
gem "haml-rails"
gem "htmlentities", "~> 4.3.4"
gem "httpclient", "~> 2.9.0"
gem "jquery-rails"
gem "jquery-ui-rails", "6.0.0"
gem "kaminari", ">= 0.15"
gem "libv8-node"
gem "marc"
gem "mini_racer", "0.6.2", platforms: :ruby
gem "net-smtp"
gem "nokogiri", "~> 1.16.7"
gem "omniauth", "~> 2.0"
gem "omniauth-saml", "~> 2.2"
gem "omniauth-rails_csrf_protection"
gem "piwik_analytics", "~> 1.0.1"
gem "protected_attributes_continued"
gem "puma", "~> 6.4"
gem "rack-cors", require: "rack/cors"
gem "rb-readline", "~> 0.5.x"
gem "redis-session-store"
gem "repost", "~> 0.4.2"
# TODO: rexml v3.3.9 is more stringent on acceptable xml. Fails with current xml format
# Before implementing, the xml structure will need to be modified to work with rexml v3.3.9
# example: Bad ❌ <"xml version='1.0'" Good ✅ <?xml version='1.0'"
gem "rexml", "~> 3.2.6"
gem "rsolr"
gem "ruby-saml", "~>1.18"
gem "rufus-scheduler"
# NOTE: sassc-rails is supposed to be a drop-in replacement for sass-rails, but removing sass-rails
# causes an error and breaks the site. There must be some dependency that is still requiring sass-rails.
gem "sass-rails", "~> 5.0"
gem "sassc-rails", ">= 2.1.0"
gem "savon", "~> 2.11.1"  # TODO: We might not need this - see https://culibrary.atlassian.net/browse/DACCESS-605 (SerialsSolutions?)
gem "sprockets" #, '~> 3.7.2'
gem "status-page"
gem "terser", "~> 1.1"
gem "ultraviolet"
gem "utf8-cleaner"
# NOTE: The URI gem is now part of the standard library in Ruby 3 and
# shouldn't need to be included explicitly. However, the bl_monkeys.rb
# file is monkey-patching the URI in a way that's incompatible with 3.x.
# This needs to be fixed before we can remove the URI gem.
gem "uri", "0.12.4"
gem "whenever", require: false
gem "yaml_db"

gem "blacklight_cornell_requests", git: "https://github.com/cul-it/blacklight-cornell-requests", tag: "v5.2"
gem "cul-folio-edge", git: "https://github.com/cul-it/cul-folio-edge", tag: "v3.2"
gem "my_account", git: "https://github.com/cul-it/cul-my-account", tag: "v2.3.5"
# gem 'blacklight_cornell_requests', :path => '/Users/matt/code/cul/d&a/blacklight-cornell-requests'
# gem 'my_account', :path => '/Users/matt/code/cul/d&a/cul-my-account'

group :development, :test do
  gem "awesome_print"
  gem "byebug"
  gem "cucumber", "~> 3.1"
  gem "cucumber-rails", :require => false # Set require = false to get rid of a warning message
  gem "database_cleaner"
  gem "guard-rspec"
  gem "meta_request"
  gem "pry"
  gem "pry-byebug"
  gem "rspec"
  gem "rspec-rails"
  gem "selenium-webdriver"
  gem "webrat"
end

group :development, :test, :integration do
  gem "brakeman"
  gem "rspec_junit_formatter"
  gem "spreewald", :git => "https://github.com/makandra/spreewald.git"
  gem "sqlite3", "~> 1.7.3"
end

group :production, :staging do
  gem "mysql2", "~> 0.5.6"
end

group :test do
  gem "capybara", "3.39.2"
  gem "capybara-email"
  # Following two gems are following the setup proposed in the RoR tutorial
  # at http://ruby.railstutorial.org/chapters/static-pages#sec-advanced_setup
  gem "libnotify", :require => false
  gem "rb-inotify", :require => false
  gem "parallel_tests"
  gem "rails-controller-testing"
  gem "simplecov", :require => false
  gem "simplecov-rcov", :require => false
  gem "vcr"
  gem "webmock"
end
