pipeline {
    agent any
    environment {
        GIT_ACCESS_TOKEN = credentials('f3b46a8a-a247-4703-baf7-c27c69656aaa')
        JENKINS_PROJECT = "blacklight-cornell-validate-pull-request"
        SOLR_URL = credentials('FOLIO_FEW_solr_url')
        STORAGE_URL = "http://digcoll.internal.library.cornell.edu:8080/fcrepo/rest"
        COLLECTIONS = "development"
        CATALOG = "http://da-prod-solr.library.cornell.edu/solr/blacklight"
    }
    stages {
        stage('Set up and run bundler') {
            steps {
                echo 'Run prelude.sh'
                sh 'jenkins/prelude.sh'
                slackSend channel: "#newcatalog", color: "#439FE0", message: "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"

            }
        }

        stage("cucumber tests") {
            steps {
                timeout(45) {
                    wrap([$class: 'Xvfb', additionalOptions: '', assignedLabels: '', autoDisplayName: true, debug: true, displayNameOffset: 0, installationName: 'default', parallelBuild: true, screen: '1024x758x24', timeout: 25]) {
                        sh 'jenkins/cucumber-features.sh features/digitalcollections/dc_item_view.feature'
                    }
                }
            }
        }

        stage('Publish Coverage') {
            steps {
                sh 'mkdir -p cover'
                publishHTML target: [
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'cover',
                reportFiles: 'excoveralls.html',
                reportName: 'Coverage-Report'
                ]
            }
        }
    }
    post {
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'cover', reportFiles: 'index.html', reportName: 'HTML Report - Coverage', reportTitles: 'Coverage Report'])
        success {
            echo "The thrill of victory"
            sh 'jenkins/report-status-to-github.sh success'
            slackSend channel: "#newcatalog", color: "#00ff00", message: "Build Successful - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }
        unsuccessful {
            echo "The agony of defeat"
            sh 'jenkins/report-status-to-github.sh failure'
            slackSend channel: "#newcatalog", color: "#ff0000", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }
    }
}